### ISSUE TITLE
待确认 Han Nom Font Set

### ISSUE THREAD

**Issue by kexplorning** [DrXie/OSFCC#13]
- http://winvnkey.sourceforge.net/webhelp/winvnkey_manual/d_set_up_winvnkey_control_panel/han_nom_fonts.htm
- http://vietunicode.sourceforge.net/fonts/fonts_hannom.html

这个字体是给越南的，不过覆盖了 CJK Unified Ideographs、CJK Unified Ideographs Extension A、CJK Unified Ideographs Extension B。

Wikipedia 上有写是 GPL 证书，在 Sourceforge 中好像找不到有关证书。

**Comment by DrXie** [comment]
我也没有找到，Windows 自带的新细明体、macOS 自带的华文字体，以及集合中的花园明朝体已能较好支持喃字，暂时不列入了。

**Comment by Kushim-Jiang** [comment]
Han Nom 的汉字部分是中易宋体，并非开源。
