### ISSUE TITLE
添加 UKIJ 系列

### ISSUE THREAD

**Issue by kexplorning** [DrXie/OSFCC#15]
http://ukij.org/fonts

这是一系列维吾尔计算机协会开发的字体。这一系列字体提供了与 CJK 混排的字体。

**Comment by DrXie** [comment]
看了一下下载链接失效了，仅 .exe 还可下载，第三方网站上有存档，暂时不添加。

**Comment by kexplorning** [comment]
@DrXie  没有失效，需要用 ukij.org 访问，www.ukij.org 链接失效了。

**Comment by DrXie** [comment]
确实如此，虽然仍可下载，但该字体系列难以单独支援一般环境下的中文排印，若是未来有较为完备的基于此字体的开源项目再行列入。
