### ISSUE TITLE
fandol 应当从此集合中移除

### ISSUE THREAD

**Issue by balthild** [DrXie/OSFCC#2]
由于其作者未在字体的元数据中标注确切的许可类型，且 CTAN 介绍页中不知何故标注了协议为 GPL with font exception，该字体长期在互联网上被误认为是自由的。

但根据作者最近才明确表述的信息，这套字体的许可协议仅授予中文 TeX 社群使用权，而非自由协议（或本项目 README.md 中所述的「开源授权协议」）。

因此，希望该集合能移除 fandol 的相关条目，以避免未知晓过其作者之发言的读者误用，而致无意中触犯许可协议限制及相关法律。

另外，[fandol 包](https://ctan.org/pkg/fandol)的页面上显示其维护者即作者，而该作者似乎并不愿意处理字体许可协议的问题。若不致烦扰，请教一下您是否知道如何才能联系 TUG 中负责管理 CTAN 上所收录宏包的人士，或认识相关人士，以明确 TUG 对此字体的权利？

相关信息来源：https://zhuanlan.zhihu.com/p/49112433 （fandol 的作者在评论区中）

**Comment by DrXie** [comment]
我也不想仔細考證了，聯繫開發者了，刪去了。
