### ISSUE TITLE
Fandol 字体

### ISSUE THREAD

**Issue by tonghuix** [DrXie/OSFCC#27]
https://ctan.org/tex-archive/fonts/fandol?lang=en
https://tug.org/TUGboat/tb34-3/tb108ma-fandol.pdf

**Comment by kexplorning** [comment]
见 #2

Fandol 字体的作者 Clerk Ma 原来以 GPL 协议发布，但近年来在多个场合中表态似乎只授权可应用在 TeX 相关的场合中（但是 CTAN 上的介绍也没变）。
