### ISSUE TITLE
I.明体

### ISSUE THREAD

**Issue by SyaoranHinata** [DrXie/OSFCC#3]
「I.明體（一點明體）」在這裏：
https://github.com/ichitenfont/I.Ming/
項目名稱可以轉爲「I.字坊（一點字坊）」了。

**Comment by DrXie** [comment]
我沒有很明白，這裡是具體的字體名稱。似乎您是創建了一個大的項目，在其中有傳承字形 (Inherited Glyphs) 標準化文件和I.Ming ( I.明體 / 一點明體 / 一点明朝 / 一点明体 )，所以好像不需要改名吧。

**Comment by SyaoranHinata** [comment]
我是對 https://github.com/DrXie/OSFCC 這頁面提供修改意見的。
1. 「I.明體」 已經交由「I.字坊（一點字坊）」負責維護，建議把它由「刻石录开源字型」改爲「I.字坊（一點字坊）開源字型」
2. 目前「I.明體」並沒有連結，建議加上「 https://github.com/ichitenfont/I.Ming/ 」這連結。

謝謝！

**Comment by DrXie** [comment]
已经修改了。
