### ISSUE TITLE
添加 更纱黑体

### ISSUE THREAD

**Issue by kexplorning** [DrXie/OSFCC#9]
https://github.com/be5invis/Sarasa-Gothic

**Comment by kexplorning** [comment]
希望注明是编程字体

**Comment by DrXie** [comment]
> 希望注明是编程字体

本集合还是面向一般中文排印需求，当然不是排除编程场景，似乎不必特别标注吧，若是有不少类似高质中文编程字体，可以单独做一个 awesome。顺便也很感谢最近提供新字体资讯啦 😄

**Comment by kexplorning** [comment]
唔。。我一般喜欢拿这个来排版代码
